# fly.toml app configuration file generated for wild-meadow-7772 on 2023-07-27T17:45:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-meadow-7772"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
